title:               Ava Chen
url:                 https://avachen.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Ava Chen
  url:               avachen.github.io
  email:             ava.chen@columbia.edu

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist